import { Header } from "@/clients/shared/components";
import { SuiClientProvider } from "@/clients/shared/providers/sui-client-provider";
import { TanstackQueryProvider } from "@/clients/shared/providers/tanstack-query";
import { WalletProvider } from "@/clients/shared/providers/wallet-provider";
import "@mysten/dapp-kit/dist/index.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TanstackQueryProvider>
          <SuiClientProvider>
            <WalletProvider>
              <div className="flex flex-col h-screen bg-[#212121]">
                <Header />
                {children}
              </div>
            </WalletProvider>
          </SuiClientProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
